---
- name: Deploy Telegram Bot with PostgreSQL
  hosts: all
  gather_facts: true
  vars:
    app_path: /opt/habit-check-bot
    docker_compose_file: "{{ app_path }}/docker-compose.yml"
    env_file: "{{ app_path }}/.env"
  
  tasks:
    - name: Create application directory
      file:
        path: "{{ app_path }}"
        state: directory
        owner: "botadmin"
        group: "botadmin"
        mode: 0775
      become: yes

    - name: Copy docker-compose.yml
      copy:
        src: "docker-compose.yml"
        dest: "{{ docker_compose_file }}"
        owner: "botadmin"
        group: "botadmin"
        mode: 0644
      become: yes

    - name: Create .env file with environment variables
      template:
        src: env.j2
        dest: "{{ env_file }}"
        owner: "botadmin"
        group: "botadmin"
        mode: 0600
      become: yes

    - name: Ensure Docker is installed
      package:
        name: docker.io
        state: present
      become: yes

    - name: Ensure Docker Compose is installed
      get_url:
        url: https://github.com/docker/compose/releases/download/v2.24.0/docker-compose-linux-x86_64
        dest: /usr/local/bin/docker-compose
        mode: 0755
      become: yes

    - name: Add botadmin user to docker group
      user:
        name: botadmin
        groups: docker
        append: yes
      become: yes

    - name: Start Docker service
      systemd:
        name: docker
        state: started
        enabled: yes
      become: yes

    - name: Pull latest images
      community.docker.docker_compose_v2:
        project_src: "{{ app_path }}"
        files:
            - "{{ docker_compose_file }}"
        pull: yes
      environment:
        TELEGRAM_BOT_TOKEN: "{{ TELEGRAM_BOT_TOKEN }}"
        POSTGRES_DB: "{{ POSTGRES_DB }}"
        POSTGRES_USER: "{{ POSTGRES_USER }}"
        POSTGRES_PASSWORD: "{{ POSTGRES_PASSWORD }}"
        POSTGRES_PORT: "{{ POSTGRES_PORT }}"

    - name: Deploy services with Docker Compose
      community.docker.docker_compose_v2:
        project_src: "{{ app_path }}"
        files:
          - "{{ docker_compose_file }}"
        state: present
        restarted: yes
        recreate: always
      environment:
        TELEGRAM_BOT_TOKEN: "{{ TELEGRAM_BOT_TOKEN }}"
        POSTGRES_DB: "{{ POSTGRES_DB }}"
        POSTGRES_USER: "{{ POSTGRES_USER }}"
        POSTGRES_PASSWORD: "{{ POSTGRES_PASSWORD }}"
        POSTGRES_PORT: "{{ POSTGRES_PORT }}"